# Site Settings
title: Bennett's Dream World
email: theadorerex@gmail.com
description: >
  I hope all is well with you. This is a website where I practice writing.
baseurl: "/personalwebsite"
url: "http://theadorerex.github.io"
twitter_username:
github_username:  theadorerex
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
